runtime: python27
api_version: 1
threadsafe: yes

env_variables:
  API_KEY: AIzaSyCqG6uEDb_igJIMoEwZSS_WsjBnGh1wQrY

handlers:

  - url: /
    static_files: dist/index.html
    upload: dist/index.html
  - url: /
    static_dir: dist
