import * as d3 from "d3";

interface Stratigraphy  {
  id: number;
  Supereon: string;
  Eon: string;
  Era: string;
  Period: string;
  Epoch: string;
  Age: string;
  GSSP: string;
  Ma: number;
  Approx: string;
  Uncertainty: any;
}

export class StratigraphyConvertor {
  static jsonToHierarchyJson(json?: Stratigraphy[]) {
    if (!json) {
      json = [
        {
          "id": 1,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Cenozoic",
          "Period": "Quaternary",
          "Epoch": "Holocene",
          "Age": "Meghalayan",
          "GSSP": "T",
          "Ma": 0.0042,
          "Approx": "",
          "Uncertainty": ""
        },
        {
          "id": 2,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Cenozoic",
          "Period": "Quaternary",
          "Epoch": "Holocene",
          "Age": "Northgrippian",
          "GSSP": "T",
          "Ma": 0.0082,
          "Approx": "",
          "Uncertainty": ""
        },
        {
          "id": 3,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Cenozoic",
          "Period": "Quaternary",
          "Epoch": "Holocene",
          "Age": "Greenlandian",
          "GSSP": "T",
          "Ma": 0.0117,
          "Approx": "",
          "Uncertainty": ""
        },
        {
          "id": 4,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Cenozoic",
          "Period": "Quaternary",
          "Epoch": "Pleistocene",
          "Age": "Upper",
          "GSSP": "",
          "Ma": 0.126,
          "Approx": "",
          "Uncertainty": ""
        },
        {
          "id": 5,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Cenozoic",
          "Period": "Quaternary",
          "Epoch": "Pleistocene",
          "Age": "Middle",
          "GSSP": "",
          "Ma": 0.781,
          "Approx": "",
          "Uncertainty": ""
        },
        {
          "id": 6,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Cenozoic",
          "Period": "Quaternary",
          "Epoch": "Pleistocene",
          "Age": "Calabrian",
          "GSSP": "T",
          "Ma": 1.8,
          "Approx": "",
          "Uncertainty": ""
        },
        {
          "id": 7,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Cenozoic",
          "Period": "Quaternary",
          "Epoch": "Pleistocene",
          "Age": "Gelasian",
          "GSSP": "T",
          "Ma": 2.58,
          "Approx": "",
          "Uncertainty": ""
        },
        {
          "id": 8,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Cenozoic",
          "Period": "Neogene",
          "Epoch": "Pliocene",
          "Age": "Piacenzian",
          "GSSP": "T",
          "Ma": 3.6,
          "Approx": "",
          "Uncertainty": ""
        },
        {
          "id": 9,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Cenozoic",
          "Period": "Neogene",
          "Epoch": "Pliocene",
          "Age": "Zanclean",
          "GSSP": "T",
          "Ma": 5.333,
          "Approx": "",
          "Uncertainty": ""
        },
        {
          "id": 10,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Cenozoic",
          "Period": "Neogene",
          "Epoch": "Miocene",
          "Age": "Messinian",
          "GSSP": "T",
          "Ma": 7.246,
          "Approx": "",
          "Uncertainty": ""
        },
        {
          "id": 11,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Cenozoic",
          "Period": "Neogene",
          "Epoch": "Miocene",
          "Age": "Tortonian",
          "GSSP": "T",
          "Ma": 11.63,
          "Approx": "",
          "Uncertainty": ""
        },
        {
          "id": 12,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Cenozoic",
          "Period": "Neogene",
          "Epoch": "Miocene",
          "Age": "Serravallian",
          "GSSP": "T",
          "Ma": 13.82,
          "Approx": "",
          "Uncertainty": ""
        },
        {
          "id": 13,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Cenozoic",
          "Period": "Neogene",
          "Epoch": "Miocene",
          "Age": "Langhian",
          "GSSP": "",
          "Ma": 15.97,
          "Approx": "",
          "Uncertainty": ""
        },
        {
          "id": 14,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Cenozoic",
          "Period": "Neogene",
          "Epoch": "Miocene",
          "Age": "Burdigalian",
          "GSSP": "",
          "Ma": 20.44,
          "Approx": "",
          "Uncertainty": ""
        },
        {
          "id": 15,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Cenozoic",
          "Period": "Neogene",
          "Epoch": "Miocene",
          "Age": "Aquitanian",
          "GSSP": "T",
          "Ma": 23.03,
          "Approx": "",
          "Uncertainty": ""
        },
        {
          "id": 16,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Cenozoic",
          "Period": "Paleogene",
          "Epoch": "Oligocene",
          "Age": "Chattian",
          "GSSP": "T",
          "Ma": 27.82,
          "Approx": "",
          "Uncertainty": ""
        },
        {
          "id": 17,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Cenozoic",
          "Period": "Paleogene",
          "Epoch": "Oligocene",
          "Age": "Rupelian",
          "GSSP": "T",
          "Ma": 33.9,
          "Approx": "",
          "Uncertainty": ""
        },
        {
          "id": 18,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Cenozoic",
          "Period": "Paleogene",
          "Epoch": "Eocene",
          "Age": "Priabonian",
          "GSSP": "",
          "Ma": 37.8,
          "Approx": "",
          "Uncertainty": ""
        },
        {
          "id": 19,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Cenozoic",
          "Period": "Paleogene",
          "Epoch": "Eocene",
          "Age": "Bartonian",
          "GSSP": "",
          "Ma": 41.2,
          "Approx": "",
          "Uncertainty": ""
        },
        {
          "id": 20,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Cenozoic",
          "Period": "Paleogene",
          "Epoch": "Eocene",
          "Age": "Lutetian",
          "GSSP": "T",
          "Ma": 47.8,
          "Approx": "",
          "Uncertainty": ""
        },
        {
          "id": 21,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Cenozoic",
          "Period": "Paleogene",
          "Epoch": "Eocene",
          "Age": "Ypresian",
          "GSSP": "T",
          "Ma": 56,
          "Approx": "",
          "Uncertainty": ""
        },
        {
          "id": 22,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Cenozoic",
          "Period": "Paleogene",
          "Epoch": "Paleocene",
          "Age": "Thanetian",
          "GSSP": "T",
          "Ma": 59.2,
          "Approx": "",
          "Uncertainty": ""
        },
        {
          "id": 23,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Cenozoic",
          "Period": "Paleogene",
          "Epoch": "Paleocene",
          "Age": "Selandian",
          "GSSP": "T",
          "Ma": 61.6,
          "Approx": "",
          "Uncertainty": ""
        },
        {
          "id": 24,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Cenozoic",
          "Period": "Paleogene",
          "Epoch": "Paleocene",
          "Age": "Danian",
          "GSSP": "T",
          "Ma": 66,
          "Approx": "",
          "Uncertainty": ""
        },
        {
          "id": 25,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Mesozoic",
          "Period": "Cretaceous",
          "Epoch": "Upper",
          "Age": "Maastrichtia",
          "GSSP": "T",
          "Ma": 72.1,
          "Approx": "",
          "Uncertainty": 0.2
        },
        {
          "id": 26,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Mesozoic",
          "Period": "Cretaceous",
          "Epoch": "Upper",
          "Age": "Campanian",
          "GSSP": "",
          "Ma": 83.6,
          "Approx": "",
          "Uncertainty": 0.2
        },
        {
          "id": 27,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Mesozoic",
          "Period": "Cretaceous",
          "Epoch": "Upper",
          "Age": "Santonian",
          "GSSP": "T",
          "Ma": 86.3,
          "Approx": "",
          "Uncertainty": 0.5
        },
        {
          "id": 28,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Mesozoic",
          "Period": "Cretaceous",
          "Epoch": "Upper",
          "Age": "Coniacian",
          "GSSP": "",
          "Ma": 89.8,
          "Approx": "",
          "Uncertainty": 0.3
        },
        {
          "id": 29,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Mesozoic",
          "Period": "Cretaceous",
          "Epoch": "Upper",
          "Age": "Turonian",
          "GSSP": "T",
          "Ma": 93.9,
          "Approx": "",
          "Uncertainty": ""
        },
        {
          "id": 30,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Mesozoic",
          "Period": "Cretaceous",
          "Epoch": "Upper",
          "Age": "Cenomanian",
          "GSSP": "T",
          "Ma": 100.5,
          "Approx": "",
          "Uncertainty": ""
        },
        {
          "id": 31,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Mesozoic",
          "Period": "Cretaceous",
          "Epoch": "Lower",
          "Age": "Albian",
          "GSSP": "T",
          "Ma": 113,
          "Approx": "a",
          "Uncertainty": ""
        },
        {
          "id": 32,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Mesozoic",
          "Period": "Cretaceous",
          "Epoch": "Lower",
          "Age": "Aptian",
          "GSSP": "",
          "Ma": 125,
          "Approx": "a",
          "Uncertainty": ""
        },
        {
          "id": 33,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Mesozoic",
          "Period": "Cretaceous",
          "Epoch": "Lower",
          "Age": "Barremian",
          "GSSP": "",
          "Ma": 129.4,
          "Approx": "a",
          "Uncertainty": ""
        },
        {
          "id": 34,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Mesozoic",
          "Period": "Cretaceous",
          "Epoch": "Lower",
          "Age": "Hauterivian",
          "GSSP": "",
          "Ma": 132.9,
          "Approx": "a",
          "Uncertainty": ""
        },
        {
          "id": 35,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Mesozoic",
          "Period": "Cretaceous",
          "Epoch": "Lower",
          "Age": "Valanginian",
          "GSSP": "",
          "Ma": 139.8,
          "Approx": "a",
          "Uncertainty": ""
        },
        {
          "id": 36,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Mesozoic",
          "Period": "Cretaceous",
          "Epoch": "Lower",
          "Age": "Berriasian",
          "GSSP": "",
          "Ma": 145,
          "Approx": "a",
          "Uncertainty": ""
        },
        {
          "id": 37,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Mesozoic",
          "Period": "Jurassic",
          "Epoch": "Upper",
          "Age": "Tithonian",
          "GSSP": "",
          "Ma": 152.1,
          "Approx": "",
          "Uncertainty": 0.9
        },
        {
          "id": 38,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Mesozoic",
          "Period": "Jurassic",
          "Epoch": "Upper",
          "Age": "Kimmeridgian",
          "GSSP": "",
          "Ma": 157.3,
          "Approx": "",
          "Uncertainty": 1
        },
        {
          "id": 39,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Mesozoic",
          "Period": "Jurassic",
          "Epoch": "Upper",
          "Age": "Oxfordian",
          "GSSP": "",
          "Ma": 163.5,
          "Approx": "",
          "Uncertainty": 1
        },
        {
          "id": 40,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Mesozoic",
          "Period": "Jurassic",
          "Epoch": "Middle",
          "Age": "Callovian",
          "GSSP": "",
          "Ma": 166.1,
          "Approx": "",
          "Uncertainty": 1.2
        },
        {
          "id": 41,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Mesozoic",
          "Period": "Jurassic",
          "Epoch": "Middle",
          "Age": "Bathonian",
          "GSSP": "T",
          "Ma": 168.3,
          "Approx": "",
          "Uncertainty": 1.3
        },
        {
          "id": 42,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Mesozoic",
          "Period": "Jurassic",
          "Epoch": "Middle",
          "Age": "Bajocian",
          "GSSP": "T",
          "Ma": 170.3,
          "Approx": "",
          "Uncertainty": 1.4
        },
        {
          "id": 43,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Mesozoic",
          "Period": "Jurassic",
          "Epoch": "Middle",
          "Age": "Aalenian",
          "GSSP": "T",
          "Ma": 174.1,
          "Approx": "",
          "Uncertainty": 1
        },
        {
          "id": 44,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Mesozoic",
          "Period": "Jurassic",
          "Epoch": "Lower",
          "Age": "Toarcian",
          "GSSP": "T",
          "Ma": 182.7,
          "Approx": "",
          "Uncertainty": 0.7
        },
        {
          "id": 45,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Mesozoic",
          "Period": "Jurassic",
          "Epoch": "Lower",
          "Age": "Pliensbachian",
          "GSSP": "T",
          "Ma": 190.8,
          "Approx": "",
          "Uncertainty": 1
        },
        {
          "id": 46,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Mesozoic",
          "Period": "Jurassic",
          "Epoch": "Lower",
          "Age": "Sinemurian",
          "GSSP": "T",
          "Ma": 199.3,
          "Approx": "",
          "Uncertainty": 0.3
        },
        {
          "id": 47,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Mesozoic",
          "Period": "Jurassic",
          "Epoch": "Lower",
          "Age": "Hettangian",
          "GSSP": "T",
          "Ma": 201.3,
          "Approx": "",
          "Uncertainty": 0.2
        },
        {
          "id": 48,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Mesozoic",
          "Period": "Triassic",
          "Epoch": "Upper",
          "Age": "Rhaetian",
          "GSSP": "",
          "Ma": 208.5,
          "Approx": "a",
          "Uncertainty": ""
        },
        {
          "id": 49,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Mesozoic",
          "Period": "Triassic",
          "Epoch": "Upper",
          "Age": "Norian",
          "GSSP": "",
          "Ma": 227,
          "Approx": "a",
          "Uncertainty": ""
        },
        {
          "id": 50,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Mesozoic",
          "Period": "Triassic",
          "Epoch": "Upper",
          "Age": "Carnian",
          "GSSP": "T",
          "Ma": 237,
          "Approx": "a",
          "Uncertainty": ""
        },
        {
          "id": 51,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Mesozoic",
          "Period": "Triassic",
          "Epoch": "Middle",
          "Age": "Ladinian",
          "GSSP": "T",
          "Ma": 242,
          "Approx": "a",
          "Uncertainty": ""
        },
        {
          "id": 52,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Mesozoic",
          "Period": "Triassic",
          "Epoch": "Middle",
          "Age": "Anisian",
          "GSSP": "",
          "Ma": 247.2,
          "Approx": "",
          "Uncertainty": ""
        },
        {
          "id": 53,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Mesozoic",
          "Period": "Triassic",
          "Epoch": "Lower",
          "Age": "Olenekian",
          "GSSP": "",
          "Ma": 251.2,
          "Approx": "",
          "Uncertainty": ""
        },
        {
          "id": 54,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Mesozoic",
          "Period": "Triassic",
          "Epoch": "Lower",
          "Age": "Induan",
          "GSSP": "T",
          "Ma": 251.902,
          "Approx": "",
          "Uncertainty": 0.024
        },
        {
          "id": 55,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Paleozoic",
          "Period": "Permian",
          "Epoch": "Lopingian",
          "Age": "Changhsingian",
          "GSSP": "T",
          "Ma": 254.14,
          "Approx": "",
          "Uncertainty": 0.07
        },
        {
          "id": 56,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Paleozoic",
          "Period": "Permian",
          "Epoch": "Lopingian",
          "Age": "Wuchiapingian",
          "GSSP": "T",
          "Ma": 259.1,
          "Approx": "",
          "Uncertainty": 0.5
        },
        {
          "id": 57,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Paleozoic",
          "Period": "Permian",
          "Epoch": "Guadalupian",
          "Age": "Capitanian",
          "GSSP": "T",
          "Ma": 265.1,
          "Approx": "",
          "Uncertainty": 0.4
        },
        {
          "id": 58,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Paleozoic",
          "Period": "Permian",
          "Epoch": "Guadalupian",
          "Age": "Wordian",
          "GSSP": "T",
          "Ma": 268.8,
          "Approx": "",
          "Uncertainty": 0.5
        },
        {
          "id": 59,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Paleozoic",
          "Period": "Permian",
          "Epoch": "Guadalupian",
          "Age": "Roadian",
          "GSSP": "T",
          "Ma": 272.95,
          "Approx": "",
          "Uncertainty": 0.11
        },
        {
          "id": 60,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Paleozoic",
          "Period": "Permian",
          "Epoch": "Cisuralian",
          "Age": "Kungurian",
          "GSSP": "",
          "Ma": 283.5,
          "Approx": "",
          "Uncertainty": 0.6
        },
        {
          "id": 61,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Paleozoic",
          "Period": "Permian",
          "Epoch": "Cisuralian",
          "Age": "Artinskian",
          "GSSP": "",
          "Ma": 290.1,
          "Approx": "",
          "Uncertainty": 0.26
        },
        {
          "id": 62,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Paleozoic",
          "Period": "Permian",
          "Epoch": "Cisuralian",
          "Age": "Sakmarian",
          "GSSP": "T",
          "Ma": 293.52,
          "Approx": "",
          "Uncertainty": 0.17
        },
        {
          "id": 63,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Paleozoic",
          "Period": "Permian",
          "Epoch": "Cisuralian",
          "Age": "Asselian",
          "GSSP": "T",
          "Ma": 298.9,
          "Approx": "",
          "Uncertainty": 0.15
        },
        {
          "id": 64,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Paleozoic",
          "Period": "Carboniferous",
          "Epoch": "Pennsylvanian  Upper",
          "Age": "Gzhelian",
          "GSSP": "",
          "Ma": 303.7,
          "Approx": "",
          "Uncertainty": 0.1
        },
        {
          "id": 65,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Paleozoic",
          "Period": "Carboniferous",
          "Epoch": "Pennsylvanian  Upper",
          "Age": "Kasimovian",
          "GSSP": "",
          "Ma": 307,
          "Approx": "",
          "Uncertainty": 0.1
        },
        {
          "id": 66,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Paleozoic",
          "Period": "Carboniferous",
          "Epoch": "Pennsylvanian  Middle",
          "Age": "Moscovian",
          "GSSP": "",
          "Ma": 315.2,
          "Approx": "",
          "Uncertainty": 0.2
        },
        {
          "id": 67,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Paleozoic",
          "Period": "Carboniferous",
          "Epoch": "Pennsylvanian  Lower",
          "Age": "Bashkirian",
          "GSSP": "T",
          "Ma": 323.2,
          "Approx": "",
          "Uncertainty": 0.4
        },
        {
          "id": 68,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Paleozoic",
          "Period": "Carboniferous",
          "Epoch": "Mississippian Upper",
          "Age": "Serpukhovian",
          "GSSP": "",
          "Ma": 330.9,
          "Approx": "",
          "Uncertainty": 0.2
        },
        {
          "id": 69,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Paleozoic",
          "Period": "Carboniferous",
          "Epoch": "Mississippian Middle",
          "Age": "Visean",
          "GSSP": "T",
          "Ma": 346.7,
          "Approx": "",
          "Uncertainty": 0.4
        },
        {
          "id": 70,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Paleozoic",
          "Period": "Carboniferous",
          "Epoch": "Mississippian Lower",
          "Age": "Tournaisian",
          "GSSP": "T",
          "Ma": 358.9,
          "Approx": "",
          "Uncertainty": 0.4
        },
        {
          "id": 71,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Paleozoic",
          "Period": "Devonian",
          "Epoch": "Upper",
          "Age": "Famennian",
          "GSSP": "T",
          "Ma": 372.2,
          "Approx": "",
          "Uncertainty": 1.6
        },
        {
          "id": 72,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Paleozoic",
          "Period": "Devonian",
          "Epoch": "Upper",
          "Age": "Frasnian",
          "GSSP": "T",
          "Ma": 382.7,
          "Approx": "",
          "Uncertainty": 1.6
        },
        {
          "id": 73,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Paleozoic",
          "Period": "Devonian",
          "Epoch": "Middle",
          "Age": "Givetian",
          "GSSP": "T",
          "Ma": 387.7,
          "Approx": "",
          "Uncertainty": 0.8
        },
        {
          "id": 74,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Paleozoic",
          "Period": "Devonian",
          "Epoch": "Middle",
          "Age": "Eifelian",
          "GSSP": "T",
          "Ma": 393.3,
          "Approx": "",
          "Uncertainty": 1.2
        },
        {
          "id": 75,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Paleozoic",
          "Period": "Devonian",
          "Epoch": "Lower",
          "Age": "Eifelian",
          "GSSP": "T",
          "Ma": 407.6,
          "Approx": "",
          "Uncertainty": 2.6
        },
        {
          "id": 76,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Paleozoic",
          "Period": "Devonian",
          "Epoch": "Lower",
          "Age": "Pragian",
          "GSSP": "T",
          "Ma": 410.8,
          "Approx": "",
          "Uncertainty": 2.8
        },
        {
          "id": 77,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Paleozoic",
          "Period": "Devonian",
          "Epoch": "Lower",
          "Age": "Lochkovian",
          "GSSP": "T",
          "Ma": 419.2,
          "Approx": "",
          "Uncertainty": 3.2
        },
        {
          "id": 78,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Paleozoic",
          "Period": "Silurian",
          "Epoch": "Pridol",
          "Age": "",
          "GSSP": "T",
          "Ma": 423,
          "Approx": "",
          "Uncertainty": 2.3
        },
        {
          "id": 79,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Paleozoic",
          "Period": "Silurian",
          "Epoch": "Ludlow",
          "Age": "Ludfordian",
          "GSSP": "T",
          "Ma": 425.6,
          "Approx": "",
          "Uncertainty": 0.9
        },
        {
          "id": 80,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Paleozoic",
          "Period": "Silurian",
          "Epoch": "Ludlow",
          "Age": "Gorstian",
          "GSSP": "T",
          "Ma": 427.4,
          "Approx": "",
          "Uncertainty": 0.5
        },
        {
          "id": 81,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Paleozoic",
          "Period": "Silurian",
          "Epoch": "Wenlock",
          "Age": "Homerian",
          "GSSP": "T",
          "Ma": 430.5,
          "Approx": "",
          "Uncertainty": 0.7
        },
        {
          "id": 82,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Paleozoic",
          "Period": "Silurian",
          "Epoch": "Wenlock",
          "Age": "Sheinwoodian",
          "GSSP": "T",
          "Ma": 433.4,
          "Approx": "",
          "Uncertainty": 0.8
        },
        {
          "id": 83,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Paleozoic",
          "Period": "Silurian",
          "Epoch": "Llandovery",
          "Age": "Telychian",
          "GSSP": "T",
          "Ma": 438.5,
          "Approx": "",
          "Uncertainty": 1.1
        },
        {
          "id": 84,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Paleozoic",
          "Period": "Silurian",
          "Epoch": "Llandovery",
          "Age": "Aeronian",
          "GSSP": "T",
          "Ma": 440.8,
          "Approx": "",
          "Uncertainty": 1.2
        },
        {
          "id": 85,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Paleozoic",
          "Period": "Silurian",
          "Epoch": "Llandovery",
          "Age": "Rhuddanian",
          "GSSP": "T",
          "Ma": 443.8,
          "Approx": "",
          "Uncertainty": 1.5
        },
        {
          "id": 86,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Paleozoic",
          "Period": "Ordovician",
          "Epoch": "Upper",
          "Age": "Hirnantian",
          "GSSP": "T",
          "Ma": 445.2,
          "Approx": "",
          "Uncertainty": 1.4
        },
        {
          "id": 87,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Paleozoic",
          "Period": "Ordovician",
          "Epoch": "Upper",
          "Age": "Katian",
          "GSSP": "T",
          "Ma": 453,
          "Approx": "",
          "Uncertainty": 0.7
        },
        {
          "id": 88,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Paleozoic",
          "Period": "Ordovician",
          "Epoch": "Upper",
          "Age": "Sandbian",
          "GSSP": "T",
          "Ma": 458.4,
          "Approx": "",
          "Uncertainty": 0.9
        },
        {
          "id": 89,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Paleozoic",
          "Period": "Ordovician",
          "Epoch": "Middle",
          "Age": "Darriwilian",
          "GSSP": "T",
          "Ma": 467.3,
          "Approx": "",
          "Uncertainty": 1.1
        },
        {
          "id": 90,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Paleozoic",
          "Period": "Ordovician",
          "Epoch": "Middle",
          "Age": "Dapingian",
          "GSSP": "T",
          "Ma": 470,
          "Approx": "",
          "Uncertainty": 1.4
        },
        {
          "id": 91,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Paleozoic",
          "Period": "Ordovician",
          "Epoch": "Lower",
          "Age": "Floian",
          "GSSP": "T",
          "Ma": 477.7,
          "Approx": "",
          "Uncertainty": 1.4
        },
        {
          "id": 92,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Paleozoic",
          "Period": "Ordovician",
          "Epoch": "Lower",
          "Age": "Tremadocian",
          "GSSP": "T",
          "Ma": 485.4,
          "Approx": "",
          "Uncertainty": 1.9
        },
        {
          "id": 93,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Paleozoic",
          "Period": "Cambrian",
          "Epoch": "Furongian",
          "Age": "Stage 10",
          "GSSP": "",
          "Ma": 489.5,
          "Approx": "a",
          "Uncertainty": ""
        },
        {
          "id": 94,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Paleozoic",
          "Period": "Cambrian",
          "Epoch": "Furongian",
          "Age": "Jiangshanian",
          "GSSP": "T",
          "Ma": 494,
          "Approx": "a",
          "Uncertainty": ""
        },
        {
          "id": 95,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Paleozoic",
          "Period": "Cambrian",
          "Epoch": "Furongian",
          "Age": "Paibian",
          "GSSP": "T",
          "Ma": 497,
          "Approx": "a",
          "Uncertainty": ""
        },
        {
          "id": 96,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Paleozoic",
          "Period": "Cambrian",
          "Epoch": "Miaolingian",
          "Age": "Guzhangian",
          "GSSP": "T",
          "Ma": 500.5,
          "Approx": "a",
          "Uncertainty": ""
        },
        {
          "id": 97,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Paleozoic",
          "Period": "Cambrian",
          "Epoch": "Miaolingian",
          "Age": "Drumian",
          "GSSP": "T",
          "Ma": 504.5,
          "Approx": "a",
          "Uncertainty": ""
        },
        {
          "id": 98,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Paleozoic",
          "Period": "Cambrian",
          "Epoch": "Miaolingian",
          "Age": "Wuliuan",
          "GSSP": "T",
          "Ma": 509,
          "Approx": "a",
          "Uncertainty": ""
        },
        {
          "id": 99,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Paleozoic",
          "Period": "Cambrian",
          "Epoch": "Series 2",
          "Age": "Stage 4",
          "GSSP": "",
          "Ma": 514,
          "Approx": "a",
          "Uncertainty": ""
        },
        {
          "id": 100,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Paleozoic",
          "Period": "Cambrian",
          "Epoch": "Series 2",
          "Age": "Stage 3",
          "GSSP": "",
          "Ma": 521,
          "Approx": "a",
          "Uncertainty": ""
        },
        {
          "id": 101,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Paleozoic",
          "Period": "Cambrian",
          "Epoch": "Terreneuvian",
          "Age": "Stage 2",
          "GSSP": "",
          "Ma": 529,
          "Approx": "a",
          "Uncertainty": ""
        },
        {
          "id": 102,
          "Supereon": "",
          "Eon": "Phanerozoic",
          "Era": "Paleozoic",
          "Period": "Cambrian",
          "Epoch": "Terreneuvian",
          "Age": "Fortunian",
          "GSSP": "T",
          "Ma": 541,
          "Approx": "",
          "Uncertainty": 1
        },
        {
          "id": 103,
          "Supereon": "Precambrian",
          "Eon": "Proterozoic",
          "Era": "Neoproterozoic",
          "Period": "Ediacaran",
          "Epoch": "",
          "Age": "",
          "GSSP": "T",
          "Ma": 635,
          "Approx": "a",
          "Uncertainty": ""
        },
        {
          "id": 104,
          "Supereon": "Precambrian",
          "Eon": "Proterozoic",
          "Era": "Neoproterozoic",
          "Period": "Cryogenian",
          "Epoch": "",
          "Age": "",
          "GSSP": "",
          "Ma": 720,
          "Approx": "a",
          "Uncertainty": ""
        },
        {
          "id": 105,
          "Supereon": "Precambrian",
          "Eon": "Proterozoic",
          "Era": "Neoproterozoic",
          "Period": "Tonian",
          "Epoch": "",
          "Age": "",
          "GSSP": "",
          "Ma": 1000,
          "Approx": "",
          "Uncertainty": ""
        },
        {
          "id": 106,
          "Supereon": "Precambrian",
          "Eon": "Proterozoic",
          "Era": "Mesoproterozoic",
          "Period": "Stenian",
          "Epoch": "",
          "Age": "",
          "GSSP": "",
          "Ma": 1200,
          "Approx": "",
          "Uncertainty": ""
        },
        {
          "id": 107,
          "Supereon": "Precambrian",
          "Eon": "Proterozoic",
          "Era": "Mesoproterozoic",
          "Period": "Ectasian",
          "Epoch": "",
          "Age": "",
          "GSSP": "",
          "Ma": 1400,
          "Approx": "",
          "Uncertainty": ""
        },
        {
          "id": 108,
          "Supereon": "Precambrian",
          "Eon": "Proterozoic",
          "Era": "Mesoproterozoic",
          "Period": "Calymmian",
          "Epoch": "",
          "Age": "",
          "GSSP": "",
          "Ma": 1600,
          "Approx": "",
          "Uncertainty": ""
        },
        {
          "id": 109,
          "Supereon": "Precambrian",
          "Eon": "Proterozoic",
          "Era": "Paleoproterozoic",
          "Period": "Statherian",
          "Epoch": "",
          "Age": "",
          "GSSP": "",
          "Ma": 1800,
          "Approx": "",
          "Uncertainty": ""
        },
        {
          "id": 110,
          "Supereon": "Precambrian",
          "Eon": "Proterozoic",
          "Era": "Paleoproterozoic",
          "Period": "Orosirian",
          "Epoch": "",
          "Age": "",
          "GSSP": "",
          "Ma": 2050,
          "Approx": "",
          "Uncertainty": ""
        },
        {
          "id": 111,
          "Supereon": "Precambrian",
          "Eon": "Proterozoic",
          "Era": "Paleoproterozoic",
          "Period": "Rhyacian",
          "Epoch": "",
          "Age": "",
          "GSSP": "",
          "Ma": 2300,
          "Approx": "",
          "Uncertainty": ""
        },
        {
          "id": 112,
          "Supereon": "Precambrian",
          "Eon": "Proterozoic",
          "Era": "Paleoproterozoic",
          "Period": "Siderian",
          "Epoch": "",
          "Age": "",
          "GSSP": "",
          "Ma": 2500,
          "Approx": "",
          "Uncertainty": ""
        },
        {
          "id": 113,
          "Supereon": "Precambrian",
          "Eon": "Archean",
          "Era": "Neoarchean",
          "Period": "",
          "Epoch": "",
          "Age": "",
          "GSSP": "",
          "Ma": 2800,
          "Approx": "",
          "Uncertainty": ""
        },
        {
          "id": 114,
          "Supereon": "Precambrian",
          "Eon": "Archean",
          "Era": "Mesoarchean",
          "Period": "",
          "Epoch": "",
          "Age": "",
          "GSSP": "",
          "Ma": 3200,
          "Approx": "",
          "Uncertainty": ""
        },
        {
          "id": 115,
          "Supereon": "Precambrian",
          "Eon": "Archean",
          "Era": "Paleoarchean",
          "Period": "",
          "Epoch": "",
          "Age": "",
          "GSSP": "",
          "Ma": 3600,
          "Approx": "",
          "Uncertainty": ""
        },
        {
          "id": 116,
          "Supereon": "Precambrian",
          "Eon": "Archean",
          "Era": "Eoarchean",
          "Period": "",
          "Epoch": "",
          "Age": "",
          "GSSP": "",
          "Ma": 4000,
          "Approx": "",
          "Uncertainty": ""
        },
        {
          "id": 117,
          "Supereon": "Precambrian",
          "Eon": "Hadean",
          "Era": "",
          "Period": "",
          "Epoch": "",
          "Age": "",
          "GSSP": "",
          "Ma": 4600,
          "Approx": "",
          "Uncertainty": ""
        }
      ]
    }

    let newJson = d3.nest<Stratigraphy>()
      .key((d) => {
        return d.Supereon
      })
      .key((d) => {
        return d.Eon
      })
      .key((d) => {
        return d.Era
      })
      .key((d) => {
        return d.Period
      })
      .key((d) => {
        return d.Epoch
      })
      .key((d) => {
        return d.Age
      })
      .entries(json);

    //Shit code
    let replacedJSON = JSON.stringify(newJson)
      .replace(new RegExp("key", "g"), "name")
      .replace(new RegExp("values", "g"), "children");

    console.log(JSON.parse(replacedJSON))

    let latestJson = {
      name: 'root',
      children: JSON.parse(replacedJSON)
    };

    return latestJson
  }
}
